### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by cybertk** [cybertk/generator-swift-framework#4]
- [ ] UITests support
- [ ] Lint with [JavaScript Standard Style](http://standardjs.com/)
- [ ] Deeper Travis Integration including
  - Create travis project
  - Provisioning travis env
  - Show user first build result
  - Ask for cert passphrase
  - Slack notification
  - Continue publish to cocoapods on git tag
- [ ] Deeper GitHub Integration including
  - Create project
  - Push first commit
- [ ] Tests generated Xcode project in CI, see [this .travis.yml](https://github.com/google/protobuf/blob/master/.travis.yml)
- [ ] Playground

**Comment by cybertk** [comment]
Replaced by [wiki](https://github.com/cybertk/generator-swift-framework/wiki/ToDo-List)
